server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: gym-management
  
  datasource:
    url: jdbc:mysql://localhost:3306/gympage?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 
    # Removido driver-class-name para auto-configuración
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: never # Deshabilitar data.sql para usar DataInitializer

# JWT Configuration
jwt:
  secret: mySecretKeyForGymManagementSystemThatIsSecureEnoughForHS512Algorithm2024
  expiration: 86400000 # 24 hours in milliseconds

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging
logging:
  level:
    com.gym: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
